### ISSUE TITLE
better sonos config can't find sonos amp

### ISSUE THREAD

**Issue by fuggalp** [originallyus/node-red-contrib-better-sonos#13]
When hitting search button to find series number for my sonos amp nothing appears.  Ive punched in my serielnumber manually but when running my flow i just get the message "device not found" 

Does the songs config not work with the songs amp ?

**Comment by Rolf-M** [comment]
Seems prety much the same issue as I've reported here
https://github.com/originallyus/node-red-contrib-better-sonos/issues/6
The search function is not working. Did you try to enter the IP Adress?

**Comment by ParkerJulius** [comment]
I have the same problem, tried entering my IP but nothing happens. It was working 1 month ago. Suddently it stoped.

**Comment by fuggalp** [comment]
I got it to work without ip address or finding it in the search field. But I have some other issues configuring the variables.

**Comment by ParkerJulius** [comment]
How did you get it to work?

**Comment by fuggalp** [comment]
I have it disconnected atm and I am at work. I'll try to give you a more detailed answer next week. But try use an inject node first before adding you're other configuration nodes

**Comment by torinnguyen** [comment]
I did a small fix related to search function. It was not working 100% all the time previously.
