### ISSUE TITLE
Config node not appearing in node red palette after installation

### ISSUE THREAD

**Issue by stupocketrocket** [originallyus/node-red-contrib-better-sonos#14]
I have installed the package and I have 4 of the 5 nodes available in the node red palette, however the config node is missing which means I can't use the other ones. Looking in the palette manager the config node has a dashed square box next to it, indicating that there is some problem. When the node red service starts on my Rasp Pi 3 there do not seem to be any errors except for their being an issue with [serial port] is this relevant  or not ?

**Comment by Rolf-M** [comment]
The config node is never visible in the palette. This is the design of node-red. The config node is used in Background to store the IP-Adress and name of your device config.
Errors around "serial port" usualy point to a to old version of node js. You should check the requirements of the "node-sonos" project, as this is used and there requirements are explained

**Comment by stupocketrocket** [comment]
Thanks for the feedback, I think I have figured it out now. I am new to node red, this is the first thing I have been looking at.
