### ISSUE TITLE
Add Spotify Tracks

### ISSUE THREAD

**Issue by ebartz** [originallyus/node-red-contrib-better-sonos#15]
Hi There, thank you for maintaining this node!

I have been tinkering around a bit and find myself getting errors when adding songs from spotify.

So from my sonos Controller it looks like this:

![image](https://user-images.githubusercontent.com/6342767/36073626-007ff1d4-0f34-11e8-9a92-64ea2c99d6a1.png)

Then I went to node and got myself the status from the current playlist which looks like this:
![image](https://user-images.githubusercontent.com/6342767/36073634-1971d3ce-0f34-11e8-87a7-de7a4be44aa4.png)

So I thought to add a track from Spotify, the only thing to do would be executing a node that plays a song from this uri: x-sonos-spotify:spotify%3atrack%3a20nDYyRNL4u5Kukzy1pL6z?sid=9&flags=8224&sn=2

But when I Try this the only result is:

![image](https://user-images.githubusercontent.com/6342767/36073655-7b1c577a-0f34-11e8-85a3-75ac477aa160.png)

Do you have any Idea, what I am doing wrong?

**Comment by ParkerJulius** [comment]
I have the same problem. And Im not able to search for my device, i have to add it with IP. Play and pause works fine!

**Comment by rephlex00** [comment]
After a ton of time playing around with this, it seems as though if a spotify track isn't playing already it will not allow you to queue a URI without a 500 error.  If something is already playing, it works fine.

`Error: HTTP response code 500 for "urn:schemas-upnp-org:service:AVTransport:1#Seek"`

It appears to be a bug in [node-sonos](https://github.com/bencevans/node-sonos/issues/142).

**Comment by K-RAD** [comment]
I'm getting the 500 error too when trying to give the uri in a payload. The issue was solved in node-sonos

**Comment by matthias-burgfried** [comment]
how can i fix this? is there a procedure?

**Comment by ebartz** [comment]
I have been working around this for some time now with just playing MP3 files. Is there still no solution to this?

If this works for someone, could you please tell us how?

**Comment by ebartz** [comment]
Dunno where this Bug exactly comes from but it works with https://flows.nodered.org/node/node-red-contrib-sonos So I am using this now.
