### ISSUE TITLE
Add grouping function

### ISSUE THREAD

**Issue by llaaccssaapp** [originallyus/node-red-contrib-better-sonos#17]
First, thank you for this great module.
It miss only a group function. Is there a way to do this?

**Comment by dgmltn** [comment]
Aka the `joinGroup` and `leaveGroup` methods from node-sonos

**Comment by llaaccssaapp** [comment]
Can you please give an example how to use this functions?

**Comment by dgmltn** [comment]
`joinGroup` and `leaveGroup` do not appear to be implemented in node-red-contrib-better-sonos, though they are implemented in node-sonos

**Comment by torinnguyen** [comment]
latest version of this node has been updated with join & leave commands.
Please refer to the node info for documentation
 
![screenshot_input](https://user-images.githubusercontent.com/767320/38601321-519ddbae-3d91-11e8-97b9-f7b1757c78d7.png)
