### ISSUE TITLE
Overwritting dialog settings with payload

### ISSUE THREAD

**Issue by ukmoose** [originallyus/node-red-contrib-better-sonos#4]
The nodes are set to allow the overwriting of the defined dialog values with msg properties.
This is the not the prefered way for node-red nodes which is where you can only send a msg property if the defined dialog value has been left unset (blank) 

See https://groups.google.com/forum/#!topic/node-red/ZFca1eslzog

**Comment by torinnguyen** [comment]
this logic was inherited from the original repository. I'll correct it.

**Comment by torinnguyen** [comment]
this has been corrected in the latest version.
