### ISSUE TITLE
Code heritage

### ISSUE THREAD

**Issue by Rolf-M** [originallyus/node-red-contrib-better-sonos#5]
Hi,
thanks for taking up this project. And thanks for taking my code fork.
I was not the author, but had the same problem, the original author doesn't seem to react any more. I needed the volume "up and down" functionality and was able to code this.

Could you check/implement the grouping and ungrouping, this seems to be implemented in the underlaying node-js, but I was not able to implement this.
I'm not the good coder, but will continue to help where I can :-)
By the way, you didn't copy my "get_volume" node, to read the current volume setting.

Regards, Rolf

**Comment by torinnguyen** [comment]
I only have 1 Sonos device at the moment. I'm waiting for the delivery of Sonos One next week. I'll be able to implement and test group/ungroup feature then.

**Comment by torinnguyen** [comment]
I combined a few features into my "Sonos Status" node. There's volume, current track, current playing status, mute.

**Comment by Rolf-M** [comment]
Hi Torin,
Thanks for your answers, I‘ll try to install your version later today and have a look.
Also thanks for taking care of the grouping. This will be very helpful feature!
Regards, Rolf
