### ISSUE TITLE
installation error 

### ISSUE THREAD

**Issue by djackbe** [originallyus/node-red-contrib-better-sonos#9]
4 Nov 22:28:22 - [info] Installing module: node-red-contrib-better-sonos, version: 0.1.9
4 Nov 22:28:56 - [info] Installed module: node-red-contrib-better-sonos
4 Nov 22:28:59 - [info] Added node types:
4 Nov 22:28:59 - [info]  - node-red-contrib-better-sonos:better-sonos-config
4 Nov 22:28:59 - [info]  - node-red-contrib-better-sonos:better-sonos-control : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode (line:4)
4 Nov 22:28:59 - [info]  - node-red-contrib-better-sonos:better-sonos-status : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode (line:4)
4 Nov 22:28:59 - [info]  - node-red-contrib-better-sonos:better-sonos-queue : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode (line:4)
4 Nov 22:28:59 - [info]  - node-red-contrib-better-sonos:better-sonos-get-queue : SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode (line:4)
4 Nov 22:29:28 - [info] Stopping flows
4 Nov 22:29:28 - [info] Stopped flows
4 Nov 22:29:28 - [info] Waiting for missing types to be registered:
4 Nov 22:29:28 - [info]  - better-sonos-status

**Comment by torinnguyen** [comment]
This has been fixed in the latest version. Please reopen this issue if it does not work for you.

**Comment by djackbe** [comment]
used a new node red docker container and it seems to work.
is there any way to get the complete output of the status back in de msg
